services:
  app:
    container_name: marketplace-app
    build: .
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    environment:
      - MONGO_URI=mongodb://mongo:27017/campus-marketplace
      - PORT=3000
    depends_on:
      - mongo
    volumes:
      - uploads-data:/app/backend/uploads

  mongo:
    image: mongo:7
    container_name: marketplace-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  mongo-data:
  uploads-data:
